services:
  - type: web
    name: n8n-seuup
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-0-us-east-1.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: "6543"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.ezbubjsdiuwmigbsmxit
      - key: DB_POSTGRESDB_PASSWORD
        value: Asd050427Asd
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin518n518
      - key: N8N_ENCRYPTION_KEY
        value: Djfhurerhr638dhfbhr7h37urhr7urhr7
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: "5678"
      - key: N8N_TRUST_PROXY
        value: "true"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: WEBHOOK_URL
        value: https://n8n-seuup.onrender.com
      - key: N8N_GOOGLE_CLIENT_ID
        value: 975198101061-ta23p75oo04d9g611vj0m5r0io0u9civ.apps.googleusercontent.com
      - key: N8N_GOOGLE_CLIENT_SECRET
        value: GOCSPX-dwol8q4Hw63Hi jKsPfW8LeG4Asd6
